on:
  push:
    branches:
      - test
      - prod
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build APK for Test Branch
        if: github.ref == 'refs/heads/test'
        run: flutter build apk --release --split-per-abi -t lib/main_dev.dart --flavor dev

      - name: Build APK for Prod Branch
        if: github.ref == 'refs/heads/prod'
        run: flutter build apk --release --split-per-abi -t lib/main_prod.dart --flavor prod

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.NEWTOKEN }}






# push to master, main, develop
# pull request on main master